### ISSUE TITLE
Velox was removed from CRAN repo by March 2020

### ISSUE THREAD

**Issue by mabar1** [tomashhurst/SpectreMAP#1]
Im trying to get SpectreMAP running on R 4.0.5. `Spectre::package.check('spatial')` did not return any missing packages. However running the SpectreMAP demo returns the error that velox is not found. I then tried to install it via github `install_github("hunzikp/velox")`, however this compilation failed for the velox package. Is there an easy way to get hold on velox?

**Comment by tomashhurst** [comment]
Hi @mabar1 , the Velox package has been depreciated, but we've found a replacement for it. Have a look at the install instructions for Spectre and SpectreMAP [here](https://immunedynamics.io/spectre/getting-started/) and see how you go! It's worth updating both packages so they are the latest version as well.

**Comment by mabar1** [comment]
Thank you for so fast answers and replacing velox. Following your link on githup, I assumed that the best is to simply remove spectre and spectreMAP and install them anew. I also cloned the repo of SpectreMAP anew. However I must have missed something, since the readme still contains the line to install velox from github, and the SpectreMAP demo.R is still using velox.

**Comment by tomashhurst** [comment]
Hi @mabar1 Hi @mabar1 , we've just release Spectre v0.5.0 which has the updated cell segmentation and spatial analysis workflows incorporated directly into Spectre (i.e. SpectreMAP is now redundant). Check out the getting started page to update Spectre, and then check out the spatial analysis page for the update instructions. Essentially you can simply use R to create the objects required to use in Ilastik, rather than having to use Anaconda/Python.
